apiVersion: v1
kind: Pod
metadata:
  name: pod-env
  namespace: roboshop

spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: project
      value: roboshop
    - name: component
      value: frontend
    - name: environment
      value: dev