apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-test
  namespace: roboshop

spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: nginx-configmap