apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    # tagging the labels(04-labels) pod to this service
    project: roboshop
    environment: dev
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
